module.exports = [
    {
      name: "My Beautiful Dark Twisted Fantasy",
      artist: "Kanye West",
      description: "What's worse: the pain or the hangover?",
      img: "https://m.media-amazon.com/images/I/713N4ZIYsEL._SL1200_.jpg",
      price: 100,
      qty: 1,
    },
    {
      name: "Ugh, those feels again",
      artist: "Snoh Aalegra",
      description: "Guarenteed to get you in your feels.",
      img: "https://media.pitchfork.com/photos/5d6567cfff9129000824150e/1:1/w_600/snoh_thosefeels.jpeg",
      price: 800,
      qty: 5,
    },
    {
      name: "Trip",
      artist: "Jhené Aiko",
      description: "An instant classic.",
      img: "https://media.pitchfork.com/photos/59cbc64777ab2e086eddda66/1:1/w_600/Screen%20Shot%202017-09-27%20at%2011.39.01%20AM.png",
      price: 500,
      qty: 1,
    },
    {
        name: "The House Is Burning",
        artist: "Isaiah Rashad",
        description: "Zay never misses.",
        img: "https://media.pitchfork.com/photos/60e5d49e74f9548edb38cbe9/1:1/w_600/Isaiah-Rashad.jpg",
        price: 7000,
        qty: 10,
      },
      {
        name: "DAMN.",
        artist: "Kendrick Lamar",
        description: "You know what Kung-Fu Kenny does.",
        img: "https://m.media-amazon.com/images/I/71FvMBLmheL._SL1200_.jpg",
        price: 1000,
        qty: 8,
      },
      {
        name: "B4.DA.$$",
        artist: "Joey Bada$$",
        description: "Brooklyn's very own.",
        img: "https://m.media-amazon.com/images/I/81kSpZbpvnL._SL1200_.jpg",
        price: 9000,
        qty: 2,
      },
      {
        name: "Malibu",
        artist: "Anderson .Paak",
        description: ".Paak just hits different.",
        img: "https://m.media-amazon.com/images/I/71O1wk5SFdL._SL1200_.jpg",
        price: 6000,
        qty: 9,
      },
      {
        name: "Currents",
        artist: "Tame Impala",
        description: "Trevor is somewhere punching the air rn.",
        img: "https://m.media-amazon.com/images/I/A1LVEJikmZL._SX522_.jpg",
        price: 4788,
        qty: 10,
      },
      {
        name: "Flower Boy",
        artist: "Tyler, The Creator",
        description: "Who dat boy?",
        img: "https://m.media-amazon.com/images/I/91OeYnLoCJL._SL1500_.jpg",
        price: 8657,
        qty: 5,
      },
      {
        name: "Born Sinner",
        artist: "J. Cole",
        description: "It's your chaining day.",
        img: "https://m.media-amazon.com/images/I/61NsLo1qoIL._AC_SS450_.jpg",
        price: 3500,
        qty: 5,
      },
      {
        name: "Take Time",
        artist: "Giveon",
        description: "Won't let you go until you grab this masterpiece.",
        img: "https://www.okayplayer.com/wp-content/uploads/2020/03/giveons-debut-ep-take-time-is-a-vintage-love-letter.jpg",
        price: 8500,
        qty: 9,
      },
      {
        name: "blkswn",
        artist: "Smino",
        description: "Go diva. Get that record.",
        img: "http://images.genius.com/58e4aa8efab906f663fd311dd2ce8201.1000x1000x1.jpg",
        price: 3456,
        qty: 7,
      },
  ];
